language: ruby
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2


env:
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.8.0"
  - PUPPET_VERSION="~> 4.1.0"
  - PUPPET_VERSION="~> 4.2.0"
  - PUPPET_VERSION="~> 4.3.0"
  - PUPPET_VERSION="~> 4.4.0"
  - PUPPET_VERSION="~> 4.5.0"

notifications:
  email: false
  flowdock: a4d40af9690ef538447d30fd7f0ececd
